function rg = random_graph
  rg = [Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf;
Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,  1,Inf,Inf,Inf,  1,Inf,  1,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf;
Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,  1,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf;
Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf;
Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,  1,  1,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf;
Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf;
Inf,Inf,Inf,Inf,  1,Inf,Inf,  1,Inf,  1,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf;
Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf;
Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf;
Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,  1,  1,  1,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf;
Inf,Inf,Inf,Inf,  1,Inf,  1,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,  1,Inf,Inf;
  1,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf;
Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf;
Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,  1,Inf,Inf,  1,Inf,  1,  1,Inf,Inf,  1,  1,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,  1,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf;
Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,  1,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf;
Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,  1,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,  1,  1,  1,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,  1,Inf;
Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,  1,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,  1,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf;
Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,  1,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf;
Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,  1,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf;
Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,  1,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,  1,  1,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf;
Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,  1,Inf,  1,Inf,Inf,Inf;
Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,  1,Inf,  1,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf;
Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf;
Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,  1,Inf,Inf,  1,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf;
Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf;
Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf;
  1,  1,  1,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf;
Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf;
Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf;
Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf;
  1,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,  1,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf;
Inf,  1,Inf,Inf,  1,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,  1,Inf,  1,Inf,Inf,Inf,Inf,  1,Inf,Inf,  1,  1,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf;
Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,  1,Inf,  1,  1,Inf,Inf;
Inf,  1,Inf,Inf,  1,  1,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,  1,Inf,Inf,Inf,  1,  1,  1,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf;
Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf;
Inf,Inf,  1,  1,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf;
Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf;
Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,  1,  1,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf;
Inf,  1,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,  1,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,  1;
Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,  1,Inf,Inf,Inf,Inf,  1;
Inf,Inf,Inf,Inf,  1,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,  1,  1,Inf,Inf;
  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf;
Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf;
Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf;
Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1;
  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf;
Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,  1,Inf,  1,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1;
Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,  1,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf;
Inf,  1,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,  1,Inf,Inf,  1,Inf,Inf,  1,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1;
Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,Inf,  1,  1,Inf,Inf,Inf,Inf,  1,Inf,  1,Inf,  1,Inf];
end
